/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 iphone_14_pro_max.glb
Author: akshatmittal (https://sketchfab.com/akshatmittal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-max-95f11f5a06604c8b9fd44046ae52a9cc
Title: iPhone 14 Pro Max
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Iphone(props) {
  const { customColor, ...rest } = props;
  const { nodes, materials } = useGLTF('/iphone_14_pro_max.glb')

  return (
    <group {...rest} dispose={null}>
      <group scale={0.01}>
        {/* Upper speaker */}
        <mesh geometry={nodes.UCttAeyROPsgmix.geometry} material={materials.KtvhjlxyToKjYkE} material-color="#000000" />

        {/* Camera sensor */}
        <mesh geometry={nodes.XbtrdVaOWYmkEiU.geometry} material={materials.YiceMpFVTpnmoaq} material-color="#000000" />

        {/* Screen */}
        <mesh geometry={nodes.YbXWdqEcjbfTKuN_0.geometry} material={materials.GFNYbWjyDVGUwJd} />

        {/* Bezel */}
        <mesh geometry={nodes.rrqFqyfckTuyRuI.geometry} material={materials.CSNzlRnZuvCyxNL} material-color="#000000" />

        {/* Unknown */}
        <mesh geometry={nodes.lxsKwuOPNvmzBKg_0.geometry} material={materials.KhJiSWFcsscOusf} />
        <mesh geometry={nodes.alSOKOYgFKIcUtR.geometry} material={materials.sWxYOtHGWTcXRMx} />

        {/* Inner */}
        <mesh geometry={nodes.FjhETOCBEeiBmch.geometry} material={materials.KtvhjlxyToKjYkE} />

        {/* Unknown */}
        <mesh geometry={nodes.AbxQOpRbGREHXRG.geometry} material={materials.IDdMwJVCyuFpUnA} />
        <mesh geometry={nodes.tWfjYtMZCfucxRt.geometry} material={materials.fdfRsQCrfvPBPfQ} />

        {/* Lower Camera Sensor */}
        <mesh geometry={nodes.vauUojKrKkLLDtY.geometry} material={materials.HvAGJeQTAiWbceX} material-color={customColor} />

        {/* Camera Background */}
        <mesh geometry={nodes.yqmgDmvGsmuPwXx_0.geometry} material={materials.bmOZLlCkCKhIIVe} material-color={customColor} />

        {/* Logo Color */}
        <mesh geometry={nodes.wjSYkRykuFHJNPw.geometry} material={materials.KxzouvBYEgdZhMo} material-color={customColor} />

        {/* Background Shade Color */}
        <mesh geometry={nodes.rJeCWUNsVVXXAbI.geometry} material={materials.psePdsxZprlxGrw} material-color={customColor} />

        {/* Back Case Color */}
        <mesh geometry={nodes.rqSonbcVVSPWFfa_0.geometry} material={materials.jFPFAvCbiqflbQV} material-color={customColor} />

        {/* Second Camera Inner Background */}
        <mesh geometry={nodes.OMkeKbwVHRBkBwM.geometry} material={materials.IkWzRHNnDaKQXIi} />

        {/* Inner Camera Outer Ring */}
        <mesh geometry={nodes.DLfIUIalXuQjJsL.geometry} material={materials.pBMikDFQfUOsKkr} />

        {/* Unknown */}
        <mesh geometry={nodes.KABLQLZRuEbcLWk.geometry} material={materials.fdfRsQCrfvPBPfQ} />

        {/* Camera Outer Ring */}
        <mesh geometry={nodes.qjXEDwnnBYwWcJn.geometry} material={materials.tfbCjiZQaZkmtHx} material-color={customColor}/>

        {/* Camera Outer Ring 2*/}
        <mesh geometry={nodes.FGDSbHbILfUmiaH.geometry} material={materials.tfbCjiZQaZkmtHx} />

        {/* Unknown */}
        <mesh geometry={nodes.jQXfQpudiYObSGp.geometry} material={materials.sWxYOtHGWTcXRMx} />

        {/* Inner Camera Outer Ring Inner Side */}
        <mesh geometry={nodes.knexoFNknstHgiO.geometry} material={materials.KtvhjlxyToKjYkE} />

        {/* Inner 2 */}
        <mesh geometry={nodes.FaUtifOQSMTXiZM.geometry} material={materials.KtvhjlxyToKjYkE} material-color={customColor} />

        {/* Camera Outer Ring Reflection Color */}
        <mesh geometry={nodes.BhvzCWikxrVeDTV.geometry} material={materials.LtesZnUOMbBEAoi} material-color={customColor}/>
        <mesh geometry={nodes.MMkajxMNWrwGQfi.geometry} material={materials.LtesZnUOMbBEAoi} />

        {/* Unknown */}
        <mesh geometry={nodes.YnrVhXEUDbStWCs.geometry} material={materials.EJpkIDZfhPDUzel} />

        {/* Bezel + Camera Circumference */}
        <mesh geometry={nodes.ePYqawqlCJbCsNi.geometry} material={materials.CSNzlRnZuvCyxNL} material-color="#000000" />

        {/* Unknown */}
        <mesh geometry={nodes.RGbIswEcCTzqNsn_0.geometry} material={materials.FlDKBWPodPcEeGy} />
        <mesh geometry={nodes.IuMgFUHIyRWENxG_0.geometry} material={materials.LcWBQfBvCzxThpp} />

        {/* Camera Flash Shade Color */}
        <mesh geometry={nodes.dNDonqESZOxUcei_0.geometry} material={materials.LUbRMhkIhuekQRK} />

        {/* Camera Outer Ring */}
        <mesh geometry={nodes.XeFHhVBtRZWPGxR.geometry} material={materials.tfbCjiZQaZkmtHx} />

        {/* Camera Flash Inner Ring */}
        <mesh geometry={nodes.nJYGEbPQybRBbiN.geometry} material={materials.tDZQoaroJfCIQtF} />

        {/* Back Case Color 2 */}
        <mesh geometry={nodes.JyAbjubWrOdfygC_0.geometry} material={materials.jFPFAvCbiqflbQV} material-color={customColor} />

        {/* Inner */}
        <mesh geometry={nodes.nxFoHsySvfcSLvp.geometry} material={materials.KtvhjlxyToKjYkE} material-color={customColor} />

        {/* Camera Outer Ring */}
        <mesh geometry={nodes.XeFHhVBtRZWPGxR.geometry} material={materials.tfbCjiZQaZkmtHx} />
        <mesh geometry={nodes.oCklTGvTZoDWJrC_0.geometry} material={materials.tfbCjiZQaZkmtHx} />

        {/* Unknown */}
        <mesh geometry={nodes.QaGkMzxNzKPcqRy.geometry} material={materials.iEhZxWeNLTDdgxm} />

        {/* Camera Inner Side */}
        <mesh geometry={nodes.KUDomTaVduCyevu.geometry} material={materials.KtvhjlxyToKjYkE} />
        
        {/* Charger Port Screws */}
        <mesh geometry={nodes.QOfJIBEXOvXfSUh.geometry} material={materials.vsSJQngPxBJTVZb} material-color="#000000"/>

        {/* Antennae Color */}
        <mesh geometry={nodes.RUMRNTkptJGDMpy.geometry} material={materials.LJBezuBxKRoHnAp} material-color={customColor} />

        {/* Bottom Speaker */}
        <mesh geometry={nodes.aYjPeBrpBRopJbp.geometry} material={materials.xHgtbqndQshkTKG} material-color="#000000"/>

        {/* Unknown */}
        <mesh geometry={nodes.BeQtuLXtpSTrzAH.geometry} material={materials.initialShadingGroup} />

        {/* Inner Charger Port Details */}
        <mesh geometry={nodes.tWBbDznHihIxXam.geometry} material={materials.OStzgRHtVBLWwiD} material-color="#000000" />

        {/* Inner Charger Port Pins */}
        <mesh geometry={nodes.PLFTnNQeqVAxicS.geometry} material={materials.BLpVAsLWNICZYGG} />

        {/* Inner Charger Port Sides */}
        <mesh geometry={nodes.GWEiavWnRxbogtw_0.geometry} material={materials.FsunUcGyajFpQmW} material-color="#000000" />

        {/* Inner Charger Port Glow */}
        <mesh geometry={nodes.RFqaqXLpuCDBIGV_0.geometry} material={materials.nJRBoEsOhzMSqCz} material-color="#000000" />

        {/* Antennae + Charger Port Color */}
        <mesh geometry={nodes.JUTNJcWwqyxbGDZ_0.geometry} material={materials.LJBezuBxKRoHnAp} />
        
        {/* Inner Charger Port */}
        <mesh geometry={nodes.BDLCJBydsNjizog_0.geometry} material={materials.fGwijctGaiRaYJC} material-color="#000000" />

        {/* Inner Speaker */}
        <mesh geometry={nodes.zPPSOvNamLQVyvv.geometry} material={materials.qEGySvwsouNnVcn} material-color="#000000" />

        {/* Camera Inner Side */}
        <mesh geometry={nodes.YPGjoywokSeoQFr.geometry} material={materials.KtvhjlxyToKjYkE} />

        {/* Mute Button */}
        <mesh geometry={nodes.MoTJNOoMxqdxNvQ.geometry} material={materials.IBtgGxCVyZhjKZM} />

        {/* Volume Button */}
        <mesh geometry={nodes.mZxrNiCtMrMjOMv.geometry} material={materials.WqbAhnIPgrrhfXS} />

        {/* Camera Circumference Color */}
        <mesh geometry={nodes.tQCDizUpBYNcvFA.geometry} material={materials.LtesZnUOMbBEAoi}  />

        {/* Inner Upper Side */}
        <mesh geometry={nodes.CAQeTxdpUcbxQyT.geometry} material={materials.KtvhjlxyToKjYkE} material-color={customColor} />

        {/* Power Button Inner Color */}
        <mesh geometry={nodes.qsTxqfACkdoWeLQ.geometry} material={materials.IBtgGxCVyZhjKZM} material-color={customColor} />

        {/* Volume Button Inner Color */}
        <mesh geometry={nodes.aVmapfDgqkPkjUf.geometry} material={materials.WqbAhnIPgrrhfXS} material-color={customColor}/>

        {/* Bezel Reflection Color */}
        <mesh geometry={nodes.lgnGJJmNebyRbHq_0.geometry} material={materials.rNCplyWedyfORFh} material-color={customColor} />
      </group>
    </group>
  )
}

useGLTF.preload('/iphone_14_pro_max.glb')

export default Iphone;